set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:Tc"
set -ga terminal-features '*:hyperlinks'
set -g mouse on
set -g set-clipboard on
set -g history-limit 50000
set -g escape-time 10
set -g word-separators " _@:"
set -g default-size 220x55
