pub mod auth;
pub mod backup;
pub mod builderd_client;
pub mod config;
pub mod grpc;
#[cfg(feature = "hostexec")]
pub mod grpc_hostexec;
pub mod grpc_server;
#[cfg(feature = "ticket")]
pub mod grpc_ticket;
#[cfg(feature = "hostexec")]
pub mod hostexec;
pub mod logging;
pub mod pool;
pub mod process;
pub mod proxy;
#[cfg(feature = "rag")]
pub mod rag;
pub mod run_opts_builder;
pub mod strategy;
pub mod stream;

pub use backup::BackupTaskManager;
pub use builderd_client::BuilderdClient;
pub use config::Config;
pub use pool::RepoPoolManager;
pub use process::{AgentContext, AgentId, ProcessConfig, ProcessManager};
pub use proxy::SquidManager;
pub use strategy::WorkerStrategy;
