name: Audit

on:
  workflow_dispatch:
  # pull_request:
  #   branches: [master]
  #   paths: [Cargo.lock]

env:
  CARGO_TERM_COLOR: always

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup workspace
        uses: ./.github/actions/setup

      - name: Run cargo audit
        run: cargo audit
